### ISSUE TITLE
Require literal '{' in patterns to be escaped

### ISSUE THREAD

**Issue by davorg** [davorg/audiofile-info-mp3-tag#1]
See https://rt.perl.org/Public/Bug/Display.html?id=128139

**Comment by choroba** [comment]
I can't find any regular expressions containing `{` in the `lib/` or `t/`. I guess the error comes from a dependency.

**Comment by davorg** [comment]
Yeah. I had a quick look earlier this morning. Nothing there are all.
To be honest, this is an obscure module that no-one ever uses. There would be far better places to spend your energy. I wouldn't be at all disappointed if you asked for a new assignment :-)

**Comment by davorg** [comment]
FYI - the regex problem is with the underlying module, MP3::Tag. See https://rt.cpan.org/Public/Bug/Display.html?id=105165

I'll see if I can get the author to fix it. I'm closing this ticket.
